require "paperback/commands/build"
require "paperback/commands/check"
require "paperback/commands/clean"
require "paperback/commands/copy_assets"
require "paperback/commands/new"
require "paperback/commands/preview"
require "paperback/commands/review"
require "paperback/commands/stats"
