AllCops:
  Includes:
    - '*.gemspec'
    - Gemfile
    - Rakefile

CollectionMethods:
  PreferredMethods:
    collect!: 'map!'
    collect: 'map'
    find: 'detect'
    find_all: 'select'
    reduce: 'inject'

Documentation:
  Enabled: false

IfUnlessModifier:
  Enabled: false

MethodCalledOnDoEndBlock:
  Enabled: true

MethodLength:
  Enabled: false

RegexpLiteral:
  MaxSlashes: 0
